version: "3"

services:
  simulator:
    image: andersonbr/radiology-simulator
    build: ./
    volumes:
      - ./src:/opt/app
      - ${LOCAL_DATASET_PATH}:/dataset
    command: python -u run.py
    # command: ls /dataset
    env_file:
      - .env
    networks:
      - dicom
    extra_hosts:
      - "host.docker.internal:host-gateway"
  pacs:
    image: jodogne/orthanc:1.12.3
    volumes:
      - ./orthanc/orthanc3.json:/etc/orthanc/orthanc.json:ro
      - ./orthanc/db:/var/lib/orthanc/db
    ports:
      - 4242:4242
      - 8042:8042
    networks:
      - dicom
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  dicom:
    external:
      name: dicom
